# Generated by Django 5.2.8 on 2025-11-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desk",
            name="location",
        ),
        migrations.AddField(
            model_name="desk",
            name="col",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="desk",
            name="row",
            field=models.IntegerField(default=0),
        ),
    ]
