# Generated by Django 5.2.8 on 2025-11-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_desk_location_desk_col_desk_row"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desk",
            name="col",
        ),
        migrations.RemoveField(
            model_name="desk",
            name="row",
        ),
        migrations.AddField(
            model_name="desk",
            name="x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="desk",
            name="y",
            field=models.FloatField(default=0.0),
        ),
    ]
