# Generated by Django 5.2.8 on 2025-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_desk_col_remove_desk_row_desk_x_desk_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="desk",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
